config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'pets', to: 'pets#index', as: 'pets'

  # RECEIVE THE FORM
  post '/pets', to: 'pets#create'

  # DISPLAY THE FORM
  get '/pets/new', to: 'pets#new', as: 'new_pet'


  get '/pets/:id', to: 'pets#show', as: 'pet'
  # EDIT RECEIVE THE FORM
  patch '/pets/:id', to: 'pets#update'
  delete '/pets/:id', to: 'pets#destroy'

  # EDIT DISPLAY THE FORM
  get '/pets/:id/edit', to: 'pets#edit', as: 'edit_pet'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['dog', 'cat', 'lizard', 'rabbit']

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    # Date.today - self.found_on
   (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show

  end

  def new
    # setup the instance to be used on the form
    @pet = Pet.new
  end

  def create
    # raise
    # initialize new instance with attributes coming from the form
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pet_path(@pet)
  end

  def edit
    # setup the instance to be used on the form

  end

  def update
    # raise

    @pet.update(pet_params)

    redirect_to pet_path(@pet)
  end

  def destroy

    @pet.destroy

    redirect_to pets_path
  end

  private

  # RAILS FILTER
  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    # {"authenticity_token"=>"[FILTERED]", "pet"=>{"name"=>"Dew", "address"=>"Mountain USA", "found_on"=>"2023-08-01", "species"=>"lizard"}, "commit"=>"Create Pet"}
    # {"name"=>"Dew", "address"=>"Mountain USA", "found_on"=>"2023-08-01", "species"=>"lizard"}
    params.require(:pet).permit(:name, :address, :found_on, :species, :adopted)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1351</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<!--
  <%= form_with model: pet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.label :found_on %>
    <%= f.date_field :found_on %>
    <%= f.label :species %>
    <%= f.select :species, Pet::SPECIES %>
    <% if pet.id %>
      <%= f.label :adopted %>
      <%= f.check_box :adopted %>
    <% end %>
    <%= f.submit %>
  <% end %>
-->

<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :found_on %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <% if pet.id %>
    <%= f.input :adopted %>
  <% end %>
<% end %>

app/views/pets/edit.html.erb
<h1>Update your pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h1>Lost pets</h1>
    <%= link_to 'Report pet', new_pet_path, class: 'btn btn-primary d-block' %>
  </div>
  <ul class='list-group'>
    <% @pets.each do |pet| %>
      <li class='list-group-item'>
        <%= link_to pet.name, pet_path(pet) %> -
        <span>Found <%= pet.found_days_ago %> days ago</span>
        <%= link_to 'Remove', pet_path(pet), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
      </li>
    <% end %>
  </ul>
</div>

app/views/pets/new.html.erb
<h1>Report a pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<div class="container">
  <h1><%= @pet.name %></h1>
  <p>Address: <%= @pet.address %></p>
  <p>Species: <%= @pet.species %></p>
  <p>Found on: <%= @pet.found_on %></p>
  <p>Adopted: <%= @pet.adopted ? 'Yes' : 'No' %></p>

  <%= link_to 'Back to all pets', pets_path %> |
  <%= link_to "Edit #{@pet.name}", edit_pet_path(@pet) %>

</div>